name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: ['1.77.0']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: Run tests
        run: cargo test --workspace

      - name: Publish INew to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}